### ISSUE TITLE
Not getting with Binary gap

### ISSUE THREAD

**Issue by udkumar** [roseliux/codility-ruby-solution#1]
Hello Roseliux,

I have entered 547 and binary is 0000001000100011, it means we have 2 binary gaps here
1-000-1-000-11

But I am getting output 3

**Comment by roseliux** [comment]
hello @udkumar sorry for the late response, this repository was just to keep my solution not planning on maintaining the repository, but feel free to share your solution and I will add to the repository

**Comment by jwaiswa7** [comment]
hello @udkumar , try this out. 

```
def solution(n)
  n =  n.to_s(2)
  n_array = n.chars
  x_array = []
  c = 0
  for i in n_array
  	if i == "0"
  	  c += 1
  	else 
  	  x_array.push c
  	  c = 0
  	end
  end
  return x_array.max
end

```

@roseliux , please let me know what you think.

**Comment by jwaiswa7** [comment]
> Hello Roseliux,
> 
> I have entered 547 and binary is 0000001000100011, it means we have 2 binary gaps here
> 1-000-1-000-11
> 
> But I am getting output 3

I think response 3 is right, according to the explanation, 3 is the longest binary gap.

**Comment by roseliux** [comment]
@jwaiswa7 It looks good but take a look at this cleaner solution 
https://github.com/roseliux/codility-ruby-solution/blob/master/Lesson%201/BinaryGap2.rb#L1

**Comment by jwaiswa7** [comment]
It looks beautiful
